In [1]:
import random
import pandas as pd
rows = ['Продолжительность эксплуатации;Количество ремонтов;Температура окр среды;Срок эксплуатации;Внезаплные отказы;Изделия с дефектами;Замена деталий;Смена обслуживания;Влажность окр среды;Страна производитель']
for i in range(100): 
  row = [str(i),
        str(random.randint(0,30)),
        str(random.randint(0,20)),
        str(random.randint(14,30)),
        str(random.randint(10,35)),
        str(random.randint(0,1)),
        str(random.randint(0,1)),
        str(random.randint(0,1)),
        str(random.randint(0,1)),
        str(random.randint(20,100)),
        str(random.randint(1,3))]
  rows.append(";".join(row))
s = "\n".join(rows)
f = open('dataset3.csv', 'w',encoding='utf8')
f.write(s)
f.close()

In [2]:
DATA = pd.read_csv("dataset3.csv", delimiter = ';')
DATA.head(100)

,Продолжительность эксплуатации,Количество ремонтов,Температура окр среды,Срок эксплуатации,Внезаплные отказы,Изделия с дефектами,Замена деталий,Смена обслуживания,Влажность окр среды,Страна производитель
0,5,18,30,33,1,0,0,1,30,1
1,23,15,27,35,0,1,0,1,77,3
2,12,15,19,12,0,0,1,0,80,2
3,14,2,24,22,1,0,1,1,50,1
4,10,13,25,35,1,1,0,0,47,3
...,...,...,...,...,...,...,...,...,...,...
95,24,13,22,19,1,1,0,0,75,1
96,18,14,14,26,1,1,1,0,68,1
97,11,10,14,24,0,0,0,1,22,3
98,22,6,24,20,0,1,1,0,66,3
99,19,0,17,14,1,1,0,1,75,2